accounts/urls.py
from django.urls import path, include
from accounts.views import *
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('user_profile/<int:pk>', user_profile, name='user_profile'),
    path('profile/settings/', profile_settings, name='profile_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view( template_name='accounts/password_reset.html', success_url = reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name= 'accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name= 'accounts/password_reset_confirm.html'), name='password_reset_confirm'),
]

coolsite/urls.py
from django.contrib import admin
from django.urls import path, include
from coolsite import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('home/', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *
app_name = 'home'


urlpatterns = [
    path('', page_home, name='page_home'),
    # path('comment/',  CommentListView.as_view(), name='comment'),
    # path('comment/<int:pk>/',  CommentDetailView.as_view(), name='comment-detail'),
    # path('comment/create/', CommentCreateView.as_view(), name='comment-create'),

    path('comment/<int:pk>/', add_comment, name='add_comment'),
    path('all_posts/', posts_view, name='blog-home'),
    path('post/<int:pk>/', post_detail, name='post-detail'),
    path('user/<int:pk>/posts', user_posts, name='user_posts'),
    path('post/create/', post_create, name='post_create'),
    path('post/<int:pk>/update/', post_update, name='post_update'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),
    path('tags/', tags_list, name='tags_list_url'),
    path('tag/<str:slug>', tag_detail, name='tag_detail_url')
    ]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from time import time


def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


class Post(models.Model):
    title = models.CharField(max_length=100 )
    post = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home:post-detail', kwargs={'pk': self.pk})


class Tag(models.Model):

    title = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    def get_absolute_url(self):
        return reverse('home:tag_detail_url', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug =gen_slug(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + ": " + str(self.content)

    def approved(self):
        self.approved = True
        self.save()

    def get_absolute_url(self):
        return reverse('home:comment-detail', kwargs={'pk': self.pk})

home/forms.py
from django import forms
from home.models import *
from django.core.exceptions import ValidationError


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'post', 'tags']

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter title', 'class': 'input_textinput'}),
            'post': forms.Textarea(attrs={'placeholder': 'Enter content text', 'class': 'input_textarea'}),

        }

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = ''
        self.fields['post'].label = ''
        self.fields['tags'].label = ''


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'post']

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter title', 'class': 'input_textinput'}),
            'post': forms.Textarea(attrs={'placeholder': 'Enter content text', 'class': 'input_textarea'}),

        }

    def __init__(self, *args, **kwargs):
        super(PostUpdateForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = ''
        self.fields['post'].label = ''


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Comment text', 'class': 'input_comments_area'}),

        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ''

home/views.py
from home.models import Post, Tag
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from home.forms import *
from django.db.models import Q
from django.views.generic import View
from django.core.paginator import Paginator


def page_home(request):
    return render(request, 'home_page.html')


# def view_home(request):
#     query = request.GET.get('search', '')
#     if query:
#         posts = Post.objects.filter(Q(title__icontains=query) | Q(post__icontains=query))
#     else:
#         posts = Post.objects.all()
#
#     context = {
#         'posts': posts
#     }
#     return render(request, 'home/view_home.html', context)
#

def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            form.instance.user = request.user
            comment.save()
            return redirect('home:post-detail', pk=post.id)
    else:
        form = CommentForm()
    context = {
        'form': form
    }
    return render(request, 'home/add_comment.html', context)


def posts_view(request):
    posts = Post.objects.all().order_by('-created')
    tags = Tag.objects.all()
    paginator = Paginator(posts, 4)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'tags': tags
    }
    return render(request, 'home/posts.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()

            context = {
                'post': post,
                'form': form
            }

            return render(request, 'home/post_detail.html', context)

    else:
        form = CommentForm()

    context = {
        'post': post,
        'form': form
    }

    return render(request, 'home/post_detail.html', context)


def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('home:blog-home')
    else:
        form = PostForm()

    context = {
        'form': form,
    }

    return render(request, 'home/post_create.html', context)


def post_update(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':

        form = PostUpdateForm(request.POST, instance=post)
        if form.is_valid():

            post.title = form['title'].value()
            post.post = form['post'].value()
            post.save()

            return redirect('home:blog-home')
    else:
        form = PostUpdateForm(instance=post)

    context = {
        'form': form,
    }

    return render(request, 'home/post_update.html', context)


def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()

    return redirect('home:blog-home')


def user_posts(request, pk):
    user = get_object_or_404(User, pk=pk)
    posts = Post.objects.filter(user=user).order_by('-created')
    context = {
        'user': user,
        'posts': posts
    }
    return render(request, 'home/user_posts.html', context)


def tags_list(request):
    context = {
        'tags': Tag.objects.all()
    }
    return render(request, 'home/tags_list.html', context)


def tag_detail(request, slug):
    tag = Tag.objects.get(slug=slug)
    context = {
        'tag': tag
    }
    return render(request, 'home/tag_detail.html', context)

home/templates/home/add_comment.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add comment</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

home/templates/home/comment.html
{% extends 'wrapper.html' %}

{% block body %}
    {% for comment in comments %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
<!--              <small class="text-muted">{{ post.created|date:"F d, Y" }}</small>-->
            </div>
            <p class="article-content">{{ comment.content }}</p>
          </div>
        </article>

    {% endfor %}
{% endblock %}

home/templates/home/comment_detail.html
{% extends 'wrapper.html' %}

{% block body %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
<!--              <small class="text-muted">{{ post.created|date:"F d, Y" }}</small>-->
            </div>
            <p class="article-content">{{ object.content }}</p>
          </div>
        </article>
{% endblock %}

home/templates/home/comment_form.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Your comments</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

home/templates/home/post_confirm_delete.html
{% extends 'wrapper.html' %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'home:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

home/templates/home/post_create.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create post</legend>
                {{ form.title }}
                {{ form.post }}
                {{ form.tags|as_crispy_field }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

home/templates/home/post_detail.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}


        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="">{{ post.user.get_full_name }}</a>
                <h2><a class="article-title" >{{ post.title }}</a></h2>

            </div>

            <p class="article-content">{{ post.post }} </p>
            <small class="">{{ post.created|date:"F d, Y" }}</small>


            <form method="POST">
                {% csrf_token %}

                    {{ form }}

                <div class="form-group">
                    <button class="btn float-right green-btn" type="submit">Submit</button>
                </div>
            </form>

              <h4 class="comment">Comments {{ post.comments.count }}:</h4>
                {% for comment in post.comments.all %}
                    <div class="article-metadata">
                  <p> By {{ comment.user }}: {{ comment.content }}</p>
                    </div>
                {% empty %}
                    <p>This post has not comments</p>

                {% endfor %}

                               {% if request.user.id == post.user.id %}
                  <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'home:post_update' pk=post.pk %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'home:post_delete' pk=post.pk %}">Delete</a>
                  </div>
                {% endif %}

          </div>


        </article>






{% endblock %}

home/templates/home/post_form.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

home/templates/home/post_update.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update post</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

home/templates/home/posts.html
{% extends 'wrapper.html' %}
{% block body %}

    {% for post in page_obj %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.user.userprofile.images.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'accounts:user_profile' pk=post.user.id %}">{{ post.user }}</a>
              <small class="text-muted">{{ post.created|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'home:post-detail' post.id%}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.post }}</p>
            Tags:
            {% for tag in post.tags.all %}
              <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
            {% endfor %}
          </div>
        </article>


    {% endfor %}

          {% if page_obj.has_previous %}
            <a class="btn arrow mb-4" href="?page={{ page_obj.previous_page_number }}">&lang;</a>
            <a class="btn green-btn mb-4" href="?page=1">First</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="btn green-btn mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <a class="btn green-btn mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="btn green-btn mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            <a class="btn arrow mb-4" href="?page={{ page_obj.next_page_number }}">&rang;</a>
          {% endif %}





{% endblock %}
{% block col-md-4 %}

<div class="content-section">
    <h3 class="text-center">Tags</h3>
        <p>Here are all the tags for the posts.</p>
          <ul class="list-group">
            {% for tag in tags %}
            <li class="list-group-item"><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></li>
            {% endfor %}
          </ul>

</div>


{% endblock%}

{% block search %}
    <form action="" class="form-search form-inline my-2 my-lg-0">
       <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
{% endblock %}

home/templates/home/tag_create.html
{% extends 'wrapper.html' %}

{% block body %}

  <form action="{% url 'home:tag_create_url' %}" method="post">
    {% csrf_token %}

    <div class="form-group">
      {% for field in form %}

      {% if field.errors %}
        <div class="alert alert-danger">
          {{ field.errors }}
        </div>
      {% endif %}

      {{ field.label }}
      {{ field }}
      {% endfor %}
    </div>

      <button type="submit" class="btn btn-primary">Create Tag</button>
  </form>

{% endblock %}

home/templates/home/tag_detail.html
{% extends 'wrapper.html' %}



{% block body %}

  <h1 class='nb-5'>Post with {{ tag.title|title }} tag: </h1>
  {% for post in tag.posts.all %}
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'accounts:user_profile' pk=user.pk%}">{{ post.user }}</a>
            <small class="text-muted">{{ post.created|date:"F d, Y" }}</small>
          </div>
          <h2><a class="article-title" href="{% url 'home:post-detail' post.id%}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.post }}</p>
        </div>
      </article>
  {% endfor %}

{% endblock %}

home/templates/home/tags_list.html
{% extends 'wrapper.html' %}
{% block body %}

  <h1 class='nb-5'>Tags:</h1>

  {% for tag in tags %}
    <h3><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></h3>
  {% endfor %}

{% endblock %}

home/templates/home/user_posts.html
{% extends 'wrapper.html' %}
{% block body %}


    <h1 class="mb-3">{{ user.username }} posts ({{ posts.count }})</h1>

    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'accounts:user_profile' pk=user.pk%}">{{ post.user }}</a>
              <small class="text-muted">{{ post.created|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'home:post-detail' post.id%}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.post }}</p>
          </div>
        </article>
    {% endfor %}


{% endblock %}