accounts/urls.py
from django.urls import path, include
from accounts.views import *
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('user_profile/<int:pk>', user_profile, name='user_profile'),
    path('profile/settings/', profile_settings, name='profile_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view( template_name='accounts/password_reset.html', success_url = reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name= 'accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name= 'accounts/password_reset_confirm.html'), name='password_reset_confirm'),
]

coolsite/urls.py
from django.contrib import admin
from django.urls import path, include
from coolsite import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('home/', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *
app_name = 'home'


urlpatterns = [
    path('', page_home, name='page_home'),
    # path('comment/',  CommentListView.as_view(), name='comment'),
    # path('comment/<int:pk>/',  CommentDetailView.as_view(), name='comment-detail'),
    # path('comment/create/', CommentCreateView.as_view(), name='comment-create'),

    path('comment/<int:pk>/', add_comment, name='add_comment'),
    path('all_posts/', posts_view, name='blog-home'),
    path('post/<int:pk>/', post_detail, name='post-detail'),
    path('user/<int:pk>/posts', user_posts, name='user_posts'),
    path('post/create/', post_create, name='post_create'),
    path('post/<int:pk>/update/', post_update, name='post_update'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),
    path('tags/', tags_list, name='tags_list_url'),
    path('tag/<str:slug>', tag_detail, name='tag_detail_url')
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    images = models.ImageField(default='default_image.png', upload_to='profile_image', blank = True)


    def __str__(self):
        return f'{self.user.username} Profile'


# Method create images a 300x300 px
    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.images.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.images.path)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile
from django.contrib.auth.forms import PasswordResetForm


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Enter name', 'class': 'input_textinput'}),
            'email': forms.TextInput(attrs={'placeholder': 'Enter new email', 'class': 'input_textinput'}),

        }

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Смена ника'
        self.fields['username'].hilp_text = 'Смена почты'
        self.fields['email'].label = 'Смена почты'




class ProfileUpdateForm(forms.ModelForm):
    images = forms.ImageField(label='')

    class Meta:

        model = UserProfile
        fields = ['images']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import *
from django.contrib.auth.models import User
from accounts.models import *
from home.models import *
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('accounts:login')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/reg_form.html', {'form': form})


# @login_required
def profile(request):
    context = {

        'users': User.objects.all(),
    }
    return render(request, 'accounts/profile.html', context)


# @login_required
def change_password(request):

        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')

        else:
            form = PasswordChangeForm(user=request.user)
            messages.success(request, 'Your new password has been saved')

        args = {'form': form}
        return render(request, 'accounts/change-password.html', args)


def user_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    posts = Post.objects.filter(user=user)

    context = {
        'user': user,
        'posts': posts
    }

    return render(request, 'accounts/user_profile.html', context)


def profile_settings(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('accounts:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm( instance=request.user.userprofile)


    context = {
        'u_form': u_form,
        'p_form': p_form,
        'users': User.objects.all(),
    }

    return render(request, 'accounts/profile_settings.html', context)

accounts/templates/accounts/change-password.html
{% extends 'wrapper.html' %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

      <button type="submit">Submit</button>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn green-btn" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'accounts:registration' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'wrapper.html' %}

{% block body %}
<div class="content-section">
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'accounts:login' %}">Log In Again</a>
        </small>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'wrapper.html' %}
{% block body %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}

    <div class="content-section">
      <div class="media">
          {% if user.userprofile.images %}
            <img class="rounded-circle account-img" src="{{ user.userprofile.images.url }}">
          {% endif %}
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
    </div>

{% endblock %}


{% block col-md-4 %}

<div class="content-section">
    <h3 class="text-center">Menu</h3>
          <ul class="list-group">
            <li class="list-group-item"><a href="{% url 'accounts:profile_settings' %}">Settings</a></li>
              <li class="list-group-item"><a href="">Friend</a></li>
              <li class="list-group-item"><a href="{% url 'home:user_posts' pk=user.id %}">Your posts</a></li>
              <li class="list-group-item"><a href="{% url 'home:post_create' %}">New Post</a></li>
          </ul>

</div>

{% endblock %}

accounts/templates/accounts/profile_settings.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
      <div class="media">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change profile</legend>

                {{ u_form.as_p }}
                {{ p_form.as_p }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Registration form</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends 'wrapper.html' %}
{% block body %}

    <div class="content-section">
      <div class="media">
          {% if user.userprofile.images %}
            <img class="rounded-circle account-img" src="{{ user.userprofile.images.url }}">
          {% endif %}
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
            {% if posts.count > 0 %}
            <h4 class="">Posts of this user: <a href="{% url 'home:user_posts' pk=user.id %}">{{ posts.count }}</a></h4>
            {% endif %}

        </div>
      </div>
    </div>


{% endblock %}