accounts/urls.py
from django.urls import path, include
from accounts.views import *
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('user_profile/<int:pk>', user_profile, name='user_profile'),
    path('profile/settings/', profile_settings, name='profile_settings'),
    path('password_reset/', auth_views.PasswordResetView.as_view( template_name='accounts/password_reset.html', success_url = reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name= 'accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name= 'accounts/password_reset_confirm.html'), name='password_reset_confirm'),
]

coolsite/urls.py
from django.contrib import admin
from django.urls import path, include
from coolsite import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('home/', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *
app_name = 'home'


urlpatterns = [
    path('', page_home, name='page_home'),
    # path('comment/',  CommentListView.as_view(), name='comment'),
    # path('comment/<int:pk>/',  CommentDetailView.as_view(), name='comment-detail'),
    # path('comment/create/', CommentCreateView.as_view(), name='comment-create'),

    path('comment/<int:pk>/', add_comment, name='add_comment'),
    path('all_posts/', posts_view, name='blog-home'),
    path('post/<int:pk>/', post_detail, name='post-detail'),
    path('user/<int:pk>/posts', user_posts, name='user_posts'),
    path('post/create/', post_create, name='post_create'),
    path('post/<int:pk>/update/', post_update, name='post_update'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),
    path('tags/', tags_list, name='tags_list_url'),
    path('tag/<str:slug>', tag_detail, name='tag_detail_url')
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    images = models.ImageField(default='default_image.png', upload_to='profile_image', blank = True)


    def __str__(self):
        return f'{self.user.username} Profile'


# Method create images a 300x300 px
    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.images.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.images.path)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile
from django.contrib.auth.forms import PasswordResetForm


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Enter name', 'class': 'input_textinput'}),
            'email': forms.TextInput(attrs={'placeholder': 'Enter new email', 'class': 'input_textinput'}),

        }

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Смена ника'
        self.fields['username'].hilp_text = 'Смена почты'
        self.fields['email'].label = 'Смена почты'




class ProfileUpdateForm(forms.ModelForm):
    images = forms.ImageField(label='')

    class Meta:

        model = UserProfile
        fields = ['images']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import *
from django.contrib.auth.models import User
from accounts.models import *
from home.models import *
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('accounts:login')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/reg_form.html', {'form': form})


# @login_required
def profile(request):
    context = {

        'users': User.objects.all(),
    }
    return render(request, 'accounts/profile.html', context)


# @login_required
def change_password(request):

        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')

        else:
            form = PasswordChangeForm(user=request.user)
            messages.success(request, 'Your new password has been saved')

        args = {'form': form}
        return render(request, 'accounts/change-password.html', args)


def user_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    posts = Post.objects.filter(user=user)

    context = {
        'user': user,
        'posts': posts
    }

    return render(request, 'accounts/user_profile.html', context)


def profile_settings(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('accounts:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm( instance=request.user.userprofile)


    context = {
        'u_form': u_form,
        'p_form': p_form,
        'users': User.objects.all(),
    }

    return render(request, 'accounts/profile_settings.html', context)

accounts/templates/wrapper.html
<!DOCTYPE html>
<html>

  <head>
    {% load static %}

    {% block title %}
    {% endblock %}

    <meta charset="UTF-8">

    <!-- Icon on site(RoflanWhat) -->
    <link rel="shortcut icon" type="image/png" href="{% static 'icon/r.ico' %}"/>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Orbitron&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">

    <meta name="viewport" content="width=device-width, intial-scale=1.0">
  </head>
  <body>




  <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" href="{% url 'home:page_home' %}">
           <img class='top-img' src="/static/4.svg" alt="logo" width="30" height="30">izzrack Blog
        </a>


        <div class="container">
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link active" href="{% url 'home:blog-home' %}">Posts</a>
                  <a class="nav-item nav-link active" href="{% url 'accounts:profile' %}">Profile</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
             <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Login</a>
                <a class="nav-item nav-link active" href="{% url 'accounts:registration' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
          {% block search %}

          {% endblock %}
      </nav>
    </header>



    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block body %}
          {% endblock %}
        </div>
        <div class="col-md-4">
        {% block col-md-4 %}
        {% endblock%}
        </div>
      </div>
    </main>




    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





  </body>

</html>